### ISSUE TITLE
TypeError: line() got an unexpected keyword argument 'joint'

### ISSUE THREAD

**Issue by AlfonsoGangemi** [Wazzaps/fingerpaint#11]
I get this error when I tap on the touchpad:

> $ fingerpaint -o test.png
Using touchpad: SYNA3082:00 06CB:8265 Touchpad
Traceback (most recent call last):
  File "$HOME/.local/bin/fingerpaint", line 8, in <module>
    sys.exit(cli())
  File "$HOME/.local/lib/python3.6/site-packages/fingerpaint/fingerpaint.py", line 288, in cli
    main(args)
  File "$HOME/.local/lib/python3.6/site-packages/fingerpaint/fingerpaint.py", line 207, in main
    make_ui(handler_loop(), scaled, devname, args)
  File "$HOME/.local/lib/python3.6/site-packages/fingerpaint/fingerpaint.py", line 89, in make_ui
    width=int(args.line_thickness * aa_factor), joint='curve', fill=(0, 0, 0)
TypeError: line() got an unexpected keyword argument 'joint'

**Comment by Wazzaps** [comment]
I'll fix this soon, in the meantime `pip3 install -U pillow` should do the trick

Thanks for the report!

**Comment by Wazzaps** [comment]
I decided to force a newer version, now with a user-friendly error message when running an old version prompting to upgrade.

Fixed in: https://github.com/Wazzaps/fingerpaint/releases/tag/v1.2.3
