### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by bombela** [Wazzaps/fingerpaint#41]
```
$ python3 -m venv fingerpaint
$ cd fingerpaint
$ source bin/activate.fish
$ pip3 install fingerpaint
$ fingerpaint
Traceback (most recent call last):
  File "/home/bombela/tmp/fingerpaint/bin/fingerpaint", line 5, in <module>
    from fingerpaint.fingerpaint import cli
  File "/home/bombela/tmp/fingerpaint/lib/python3.12/site-packages/fingerpaint/fingerpaint.py", line 6, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

Python 3.12.3
Ubuntu 24.04

**Comment by Mammad900** [comment]
Workaround: edit the source file and comment out these lines:
https://github.com/Wazzaps/fingerpaint/blob/b71b04627b8842282d43e2f60bc476e2971a2e49/fingerpaint/fingerpaint.py#L6
https://github.com/Wazzaps/fingerpaint/blob/b71b04627b8842282d43e2f60bc476e2971a2e49/fingerpaint/fingerpaint.py#L155-L158
However this will break unrestricting touchpad access (`Touchpad access is currently restricted. Would you like to unrestrict it?`), which can be worked around by manually running [data/fix_permissions.sh](https://github.com/Wazzaps/fingerpaint/blob/b71b04627b8842282d43e2f60bc476e2971a2e49/fingerpaint/data/fix_permissions.sh)
